### ISSUE TITLE
error X3003: redefinition of 'VertexOutput_main::member'

### ISSUE THREAD

**Issue by eaglekindoms** [gfx-rs/wgpu#1870]
**Description**
Hello, 
When I update the wgpu from 0.9 to 0.10, I ran into a bug: 
D3DCompile error (0x80004005): D:\xxx\polygon.vert.spv(39,12-17): error X3003: redefinition of 'VertexOutput_main::member'

Could you please tell me what is wrong with this, my code does not experience these problems in version 0.9.

Thanks,

**Platform**
win10, rtx2060, wgpu-0.10.1

It's the log:
```

2021-08-27 16:31:36,096 WARN  [wgpu_hal::dx12::device] Naga generated shader for "main" at Vertex:
struct NagaConstants {
    int base_vertex;
    int base_instance;
    uint other;
};
ConstantBuffer<NagaConstants> _NagaConstants: register(b0);

struct gl_PerVertex {
    float4 gl_Position : SV_Position;
    float gl_PointSize : PSIZE;
    float gl_ClipDistance[1] : SV_ClipDistance;
    float gl_CullDistance[1] : SV_CullDistance;
};

struct type18 {
    linear float2 member : LOC1;
    linear float4 member1 : LOC0;
    linear float member2 : LOC3;
    linear float member3 : LOC2;
    float4 gl_Position : SV_Position;
    float gl_PointSize : PSIZE;
    float gl_ClipDistance[1] : SV_ClipDistance;
    float gl_CullDistance[1] : SV_CullDistance;
};

static float2 v_pos = (float2)0;
static float2 a_pos1 = (float2)0;
static float4 v_color = (float4)0;
static float4 a_color1 = (float4)0;
static float v_radius = (float)0;
static float a_radius1 = (float)0;
static float v_edge = (float)0;
static uint a_edge1 = (uint)0;
static gl_PerVertex perVertexStruct = { float4(0.0, 0.0, 0.0, 1.0), 1.0, { 0.0 }, { 0.0 } };
static int gl_VertexIndex1 = (int)0;

struct VertexOutput_main {
    float4 member : LOC0;
    float2 member : LOC1;
    float member : LOC2;
    float member : LOC3;
    float4 gl_Position : SV_Position;
    float gl_ClipDistance : SV_ClipDistance;
    float gl_CullDistance : SV_CullDistance;
    float gl_PointSize : PSIZE;
};

void main1()
{
    float2 indexable[4] = {(float2)0,(float2)0,(float2)0,(float2)0};

    float2 _expr26 = a_pos1;
    v_pos = _expr26;
    float4 _expr27 = a_color1;
    v_color = _expr27;
    float _expr28 = a_radius1;
    v_radius = _expr28;
    uint _expr29 = a_edge1;
    v_edge = float(_expr29);
    int _expr31 = gl_VertexIndex1;
    {
        float2 _result[4]={ float2(-1.0, 1.0), float2(1.0, 1.0), float2(-1.0, -1.0), float2(1.0, -1.0) };
        for(int _i=0; _i<4; ++_i) indexable[_i] = _result[_i];
    }
    float2 _expr33 = indexable[_expr31];
    perVertexStruct.gl_Position = float4(_expr33.x, _expr33.y, 0.0, 1.0);
    return;
}

VertexOutput_main main(float2 a_pos : LOC0, float4 a_color : LOC1, float a_radius : LOC2, uint a_edge : LOC3, uint gl_VertexIndex : SV_VertexID)
{
    a_pos1 = a_pos;
    a_color1 = a_color;
    a_radius1 = a_radius;
    a_edge1 = a_edge;
    gl_VertexIndex1 = int((_NagaConstants.base_vertex + gl_VertexIndex));
    main1();
    float2 _expr20 = v_pos;
    float4 _expr21 = v_color;
    float _expr22 = v_radius;
    float _expr23 = v_edge;
    float4 _expr24 = perVertexStruct.gl_Position;
    float _expr25 = perVertexStruct.gl_PointSize;
    float _expr26[1] = perVertexStruct.gl_ClipDistance;
    float _expr27[1] = perVertexStruct.gl_CullDistance;
    const type18 type18_ = { _expr20, _expr21, _expr22, _expr23, _expr24, _expr25, _expr26, _expr27 };
    const VertexOutput_main type18_1 = { type18_.member1, type18_.member, type18_.member3, type18_.member2, type18_.gl_Position, type18_.gl_ClipDistance, type18_.gl_CullDistance, type18_.gl_PointSize };
    return type18_1;
}

2021-08-27 16:31:36,096 WARN  [wgpu::backend::direct] Shader translation error for stage VERTEX: D3DCompile error (0x80004005): D:\code\rust-workplace\LemoGUI\shader_c\polygon.vert.spv(39,12-17): error X3003: redefinition of 'VertexOutput_main::member'
 
2021-08-27 16:31:36,097 WARN  [wgpu::backend::direct] Please report it to https://github.com/gfx-rs/naga
2021-08-27 16:31:36,097 ERROR [wgpu::backend::direct] wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `Render Pipeline`
    Internal error in VERTEX shader: D3DCompile error (0x80004005): D:\code\rust-workplace\xxx\shader_c\polygon.vert.spv(39,12-17): error X3003: redefinition of 'VertexOutput_main::member'

```
