### ISSUE TITLE
Naga tests don't build without features

### ISSUE THREAD

**Issue by jimblandy** [gfx-rs/wgpu#7038]
#6938 (use hashbrown in more crates) causes `cargo nextest run` in the `naga` subdirectory to fail:

```
cargo nextest run
   Compiling naga v24.0.0 (/home/jimb/wgpu/naga)
error[E0277]: the trait bound `hashbrown::set::HashSet<spirv::Capability, BuildHasherDefault<rustc_hash::FxHasher>>: Deserialize<'_>` is not satisfied
    --> naga/tests/snapshots.rs:45:19
     |
45   |     capabilities: naga::FastHashSet<spirv::Capability>,
     |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Deserialize<'_>` is not implemented for `hashbrown::set::HashSet<spirv::Capability, BuildHasherDefault<rustc_hash::FxHasher>>`
     |
```

I think the issue here is that serde itself implements `Deserialize` for `std::hash::HashSet`, but not `hashbrown::HashSet`.

Apparently CI doesn't run Naga tests without features.

**Comment by brody2consult** [comment]
My one suggestion is that you can do nextest on a single crate from the project root directory with a command like this:

```sh
cargo nextest run -p naga
```

and yes, this IS also broken by #6938. I would personally favor both updating CI to test these & update README to clarify this. I would be happy to contribute these updates, if needed.
