### PR TITLE
[naga] Use cfg aliases to enable `naga::back::continue_forward`.

### LINKED ISSUE #6063: Naga fails to build: "unresolved import `back::continue_forward`"
Naga fails to build as follows (which happens to be the way Firefox uses it):

```console
$ cargo build --target=x86_64-pc-windows-msvc --features="dx12 vulkan"
   Compiling naga v22.0.0 (/home/jimb/rust/wgpu/naga)
   Compiling wgpu-core v22.0.0 (/home/jimb/rust/wgpu/wgpu-core)
   Compiling d3d12 v22.0.0 (/home/jimb/rust/wgpu/d3d12)
error[E0432]: unresolved import `back::continue_forward`
    --> naga/src/back/hlsl/writer.rs:1574:19
     |
1574 |         use back::continue_forward::ExitControlFlow;
     |                   ^^^^^^^^^^^^^^^^ could not find `continue_forward` in `back`

error[E0433]: failed to resolve: could not find `continue_forward` in `back`
   --> naga/src/back/hlsl/writer.rs:107:33
    |
107 |             continue_ctx: back::continue_forward::ContinueCtx::default(),
    |                                 ^^^^^^^^^^^^^^^^ could not find `continue_forward` in `back`

error[E0433]: failed to resolve: could not find `continue_forward` in `back`
   --> naga/src/back/hlsl/mod.rs:330:25
    |
330 |     continue_ctx: back::continue_forward::ContinueCtx,
    |                         ^^^^^^^^^^^^^^^^ could not find `continue_forward` in `back`

Some errors have detailed explanations: E0432, E0433.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `naga` (lib) due to 3 previous errors
$ 
```

### PR DESCRIPTION
**Pull request by jimblandy**
Rather than `feature = "blah"`, use the new `cfg` identifiers introduced by the `cfg_aliases` invocation in `naga/build.rs` to decide whether to compile the `naga::back::continue_forward` module, which is only used by the GLSL and HLSL backends.

The `hlsl_out` `cfg` identifer has a more complex condition than just `feature = "hlsl-out"`, introduced by #5919.

Fixes #6063.

### CODE REVIEW

**Review by ErichDonGubler — APPROVED** [review]
Só vai!

**Comment by jimblandy** [comment]
Obrigado por dar uma olhada!

**Review by teoxoy — APPROVED** [review]
